# -*- coding: utf-8 -*-
"""generate_narrative

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mhSjtHqzNcMgKi5SEnQ7yOii_Mrj26h4

# *PART 3 - GENAI - Powered Insight Narrator*

1.	Task 1 - narrator/findings.json

2.	Task 2 - generate_scr_narrative(findings: dict) -> dict

3.	Task 3 - Parameter locking and error handling

4.	Task 4 - Offline fallback path

5.	Task 5 - Numeric accuracy checklist

6.	Task 6 - README pipeline write-up
"""

#	Task 1 - narrator/findings.json

print("--JSON file conducting findings generated in clean_and_eda python file--")

from google import genai
from google.colab import userdata
from google.genai import types

# Get Gemini API key securely from Google Colab Secrets
key = userdata.get('MV_API_KEY')

# Create Gemini client

# Create Gemini client with timeout configuration
client = genai.Client(
    api_key=key,
    http_options=types.HttpOptions(timeout=15000)
)

import json
import pandas as pd

# Load cleaned orders
orders_clean = pd.read_csv("/content/orders_clean.csv")

# Load verified findings
with open("/content/findings.json", "r") as f:
    findings = json.load(f)

# Task 2 - generate_scr_narrative(findings: dict)

def generate_scr_narrative(findings: dict) -> dict:

    system_instruction = """
You are a Data Analyst on Mamaearth's Growth Analytics Team.
Audience: Head of Data Analytics.

Write a concise, professional business narrative using the SCR framework.
Use exactly three labeled sections:
SITUATION
COMPLICATION
RESOLUTION

Maximum length: 210 words.

Evidence and accuracy rules:
- Use only facts and numbers present in the findings dictionary.
- Do not invent statistics, causes, correlations, or business outcomes.
- Preserve all numerical values and their meaning.
- Format INR currency values consistently to two decimal places.
- Include sample sizes when discussing small or high-risk segments.
- Specifically, state that the Tier 2 high-value COD result is
  7 returns out of 8 orders, if these figures are provided.
- Describe findings as observed patterns, not proof of causation.
- Do not claim that a recommendation will definitely reduce returns,
  increase revenue, or reduce costs.
- Clearly distinguish verified results from proposed actions.
- Make recommendations measurable and suitable for a pilot.

Return only the three labeled narrative sections.
Do not include JSON, introductory text, or a conclusion outside SCR.
"""


    user_prompt = f"""
      Write a concise business story using these verified findings:

      {json.dumps(findings, indent=2)}

      SITUATION:
      Approximately 30-40 words.
      Introduce the cleaned revenue baseline and the purpose of the
      analytics pipeline. Avoid unsupported claims about business performance.

      COMPLICATION:
      Approximately 70-90 words.
      Explain:
      - The revenue reconciliation difference associated with duplicate records.
      - Return-rate differences across COD, CARD, and UPI.
      - The highest-risk COD city-tier segment.
      - The high-value COD finding across city tiers.
      - Include the sample size for the Tier 2 high-value segment.

      RESOLUTION:
      Approximately 50-70 words.
      Explain the corrected monthly revenue trend and the true peak month.
      Recommend a measurable pilot for high-value COD orders in Tier 2 cities.
      Mention that additional data is needed to validate the observed pattern.
      Do not present the recommendation as a proven solution.

      Keep all three sections within 210 words.
      Use the exact labels SITUATION, COMPLICATION, and RESOLUTION.
      """


    # Task 3 - Parameter locking and error handling
    try:
        response = client.models.generate_content(
            model="gemini-3.1-flash-lite",
            contents=user_prompt,
            config=types.GenerateContentConfig(
                system_instruction=system_instruction,
                temperature=0.0,
                max_output_tokens=400
            )
        )


        if not response.text:
            return {
                "status": "error",
                "success": False,
                "narrative": None,
                "message": "Empty response"
            }

        return {
            "status": "success",
            "narrative": response.text,
            "tokens": (
                response.usage_metadata.total_token_count
                if response.usage_metadata else None
            )
        }

    except Exception as err:
        return {
            "status": "error",
            "success": False,
            "narrative": None,
            "message": str(err)
        }


# Try the online narrative first; fall back to offline if unavailable
if key:
    result = generate_scr_narrative(findings)
else:
    result = {
        "status": "error",
        "message": "No API key available"
    }

if result["status"] != "success":
    print("Online generation unavailable. Using offline fallback.")
    result = generate_scr_narrative_offline(findings)

print(json.dumps(result, indent=2))

"""**SITUATION**

Our analytics pipeline has established a cleaned total revenue baseline of INR 97,358.30. This assessment reconciles raw data to ensure accurate reporting, providing a foundation for evaluating order performance and return patterns across our sales.

**COMPLICATION**

Duplicate records created a reconciliation delta of INR 2,501.90. Analysis reveals significant variance in return rates: COD (44.40%) exceeds CARD (14.70%) and UPI (18.90%). The highest-risk segment is COD orders in Tier 2 cities, with a 54.50% return rate. Specifically, high-value COD orders show an elevated return pattern, most notably in Tier 2 cities where we observed 7 returns out of 8 orders. These patterns highlight a concentration of risk within specific payment and geographic segments.

**RESOLUTION**

Data correction reveals that January 2026 revenue was inflated; the true peak month is March 2026, with INR 20,318.90 in revenue. I recommend a measurable pilot program targeting high-value COD orders in Tier 2 cities to monitor return outcomes. Additional data is required to validate these observed patterns and determine if this pilot approach effectively addresses the identified segment risks.
"""

## 4.	Task 4 - Offline fallback path

def generate_scr_narrative_offline(findings: dict) -> dict:
    """
    Generate an SCR narrative locally without an API call.
    Uses verified values from findings.json.
    """

    cleaned_revenue = findings["cleaned_total_revenue_inr"]
    raw_revenue = findings["raw_total_revenue_inr"]
    reconciliation_delta = findings["duplicate_reconciliation_delta_inr"]

    payment_rates = findings["return_rate_by_payment"]
    highest_risk = findings["highest_risk_segment"]
    peak_month = findings["true_peak_month"]
    inflated_month = findings["outlier_inflated_month"]

    cod_value_rates = findings["cod_return_rate_by_value"]

    tier_value_data = findings["cod_return_rate_by_tier_and_value"]

    tier2_high_value = next(
        item for item in tier_value_data
        if item["city_tier"] == 2
        and item["value_group"] == "High Value"
    )

    narrative = f"""
SITUATION

The Mamaearth Returns & Growth Intelligence Pipeline established a cleaned
revenue baseline of INR {cleaned_revenue:,.2f}, compared with raw revenue of
INR {raw_revenue:,.2f}. The analysis evaluates payment-method return patterns
and monthly revenue trends.

COMPLICATION

Duplicate records account for a reconciliation difference of
INR {reconciliation_delta:,.2f}. Return rates vary by payment method:
COD {payment_rates['COD']:.1f}%, CARD {payment_rates['CARD']:.1f}%,
and UPI {payment_rates['UPI']:.1f}%. The highest-risk segment is
{highest_risk['payment_method']} in Tier {highest_risk['city_tier']} cities,
with a return rate of {highest_risk['return_rate_pct']:.1f}%.
High-value COD orders in Tier 2 cities show a return rate of
{tier2_high_value['return_rate_pct']:.1f}%:
{tier2_high_value['returned_orders']} returns out of
{tier2_high_value['total_orders']} orders.

RESOLUTION

After correcting for the revenue outlier, {peak_month['month']} was the
true peak month, with revenue of INR {peak_month['revenue_inr']:,.2f}.
The apparent peak in {inflated_month['month']} was INR
{inflated_month['apparent_revenue_inr']:,.2f}, compared with corrected
revenue of INR {inflated_month['corrected_revenue_inr']:,.2f}.
A suitable next step is to pilot interventions for high-value COD orders
in Tier 2 cities and validate the observed pattern with additional data.
""".strip()

    return {
        "status": "success",
        "narrative": narrative,
        "tokens": 0
    }

## Testing the offline function

offline_result = generate_scr_narrative_offline(findings)

print(json.dumps(offline_result, indent=2))

assert offline_result["status"] == "success"
assert "SITUATION" in offline_result["narrative"]
assert "COMPLICATION" in offline_result["narrative"]
assert "RESOLUTION" in offline_result["narrative"]

print("\nOffline fallback test passed.")

from pathlib import Path

# Check files currently available in Google Colab
for path in [
    Path("/content/orders_clean.csv"),
    Path("/content/findings.json"),
    Path("/content/clean_and_eda.py"),
    Path("/content/visualize.py"),
    Path("/content/generate_narrative.py")
]:
    print(f"{'FOUND' if path.exists() else 'MISSING'}: {path}")

from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.ticker import FormatStrFormatter

# Colab paths
DATA_DIR = Path("/content")
VISUALIZATION_DIR = DATA_DIR / "visualizations"
VISUALIZATION_DIR.mkdir(parents=True, exist_ok=True)

# Load cleaned data
orders_clean = pd.read_csv(DATA_DIR / "orders_clean.csv")

# -------------------------------
# Chart 1: Return rate by payment
# -------------------------------
payment_summary = (
    orders_clean.groupby("payment_method")["returned"].mean() * 100
).reindex(["COD", "CARD", "UPI"])

colors = {"COD": "red", "CARD": "blue", "UPI": "green"}

fig, ax = plt.subplots(figsize=(9, 6))
bars = ax.bar(
    payment_summary.index,
    payment_summary.values,
    color=[colors[p] for p in payment_summary.index]
)

for bar, payment in zip(bars, payment_summary.index):
    ax.text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height() + 1,
        f"{payment_summary[payment]:.1f}%",
        ha="center"
    )

ax.set_title("Return Rate based on Payment Method")
ax.set_xlabel("Payment Method")
ax.set_ylabel("Return Rate (%)")
ax.yaxis.set_major_formatter(FormatStrFormatter("%.2f"))
ax.spines[["top", "right"]].set_visible(False)
ax.set_ylim(0, max(payment_summary.values) + 10)
fig.tight_layout()
fig.savefig(
    VISUALIZATION_DIR / "return_rate_by_payment.png",
    dpi=150
)
plt.show()
plt.close(fig)

# ---------------------------------
# Chart 2: Corrected monthly revenue
# ---------------------------------
orders_clean["order_date"] = pd.to_datetime(
    orders_clean["order_date"], errors="coerce"
)

monthly_data = orders_clean.copy()

# Exclude flagged quantity outliers when the flag is available
if "is_outlier" in monthly_data.columns:
    monthly_data = monthly_data[
        ~monthly_data["is_outlier"].fillna(False).astype(bool)
    ]

monthly_revenue = (
    monthly_data.groupby(monthly_data["order_date"].dt.to_period("M"))[
        "order_value"
    ].sum()
)

fig, ax = plt.subplots(figsize=(10, 6))
ax.plot(
    monthly_revenue.index.astype(str),
    monthly_revenue.values,
    marker="o"
)
ax.set_title("Monthly Order Value – Corrected for Outliers")
ax.set_xlabel("Month")
ax.set_ylabel("Revenue (INR)")
ax.tick_params(axis="x", rotation=45)
ax.spines[["top", "right"]].set_visible(False)
fig.tight_layout()
fig.savefig(
    VISUALIZATION_DIR / "monthly_revenue_trend.png",
    dpi=150
)
plt.show()
plt.close(fig)

# -----------------------------------------------
# Chart 3: COD returns by city tier and order value
# -----------------------------------------------
cod_orders = orders_clean[
    orders_clean["payment_method"] == "COD"
].copy()

cod_orders["value_group"] = pd.qcut(
    cod_orders["order_value"],
    q=3,
    labels=["Low Value", "Medium Value", "High Value"],
    duplicates="drop"
)

segment_summary = cod_orders.groupby(
    ["city_tier", "value_group"],
    observed=True
).agg(
    total_orders=("returned", "count"),
    returned_orders=("returned", "sum"),
    return_rate=("returned", "mean")
).reset_index()

segment_summary["return_rate_pct"] = (
    segment_summary["return_rate"] * 100
)

fig, ax = plt.subplots(figsize=(10, 6))
sns.barplot(
    data=segment_summary,
    x="city_tier",
    y="return_rate_pct",
    hue="value_group",
    hue_order=["Low Value", "Medium Value", "High Value"],
    ax=ax
)

for container in ax.containers:
    ax.bar_label(container, fmt="%.1f%%", padding=3, fontsize=9)

ax.set_title("COD Return Rate by City Tier and Order Value")
ax.set_xlabel("City Tier")
ax.set_ylabel("Return Rate (%)")
ax.set_ylim(0, 105)
ax.spines[["top", "right"]].set_visible(False)
ax.legend(title="Order Value", bbox_to_anchor=(1.02, 1), loc="upper left")
fig.tight_layout()
fig.savefig(
    VISUALIZATION_DIR / "cod_return_rate_by_segment.png",
    dpi=150,
    bbox_inches="tight"
)
plt.show()
plt.close(fig)

# Verify all three files were generated
expected_charts = [
    "return_rate_by_payment.png",
    "monthly_revenue_trend.png",
    "cod_return_rate_by_segment.png"
]

for filename in expected_charts:
    path = VISUALIZATION_DIR / filename
    assert path.exists() and path.stat().st_size > 0, (
        f"Chart missing or empty: {filename}"
    )
    print(f"PASS: {filename}")

print("\nAll three visualisation files generated successfully.")