# -*- coding: utf-8 -*-
"""clean_and_eda.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iB6vCBRZA5X7NuNn-bxXBEaOcnNP_35O

# *Part 2 - Python/Pandas Data Wrangling & EDA*

1.	Task 1 - Load and inspect
2.	Task 2 - Standardize payment_method casing
3.	Task 3 - Remove duplicate orders
4.	Task 4 - Impute missing values
5.	Task 5 - Merge and reconcile against Part 1
6.	Task 6 - IQR outlier detection on quantity
7.	Task 7 - Hypothesis: does COD have a higher return rate?
8.	Task 8 - Multi-level segmentation
9.	Task 9 - Correlation analysis
10.	Task 10 - Outlier-corrected time series
11.	Task 11 - Two visualizations (analysis/visualize.py)
"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import statistics as stats
import seaborn as sns

## LOAD AND INSPECT

customers = pd.read_csv('/content/DATA_CUSTOMERS.csv')
print("=== CUSTOMERS DATA SHAPE ===")
print(customers.shape)

orders = pd.read_csv('/content/DATA_ORDERS.csv')
print("=== ORDERS DATA SHAPE ===")
print(orders.shape)

products = pd.read_csv('/content/DATA_PRODUCTS.csv')
print("=== PRODUCTS DATA SHAPE ===")
print(products.shape)

## Before cleaning
orders.head()

## Task 2 - Standardize payment_method casing

## Correct casing of payment_method to make it more cohesive
orders['payment_method'] = orders['payment_method'].str.strip().str.upper()

print(f"PAYMENT METHOD: {orders['payment_method'].unique()}")

## Payment_Method head counts
orders['payment_method'].value_counts()

## Task 3 - Remove duplicate orders

# Identify duplicates using the natural key.
# order_id is excluded because O0176-O0180 have different IDs by design.
duplicate_mask = orders.duplicated(
    subset=[
        'customer_id', 'product_id', 'order_date', 'quantity',
        'discount_pct', 'payment_method', 'rating', 'returned'
    ],
    keep='first'
)

# Print the duplicate order IDs
print("DUPLICATE ORDER IDs:")
print(orders.loc[duplicate_mask, 'order_id'])

# Remove duplicate rows
orders_clean = orders[~duplicate_mask].copy()

# Check the cleaned shape
print("CLEANED DATA SHAPE:", orders_clean.shape)

## Task 4 - Impute missing values

# Fill missing discount values with 0
orders_clean['discount_pct'] = orders_clean['discount_pct'].fillna(0)

# Calculate median rating before imputation
rating_median = orders_clean['rating'].median()
print("MEDIAN RATING:", rating_median)

# Count the rows which were missing the values for imputation
print("--- Missing Values Before Imputation ---")
print(orders[['discount_pct', 'rating']].isnull().sum())

# Fill missing ratings with the median
orders_clean['rating'] = orders_clean['rating'].fillna(rating_median)

# Check for remaining missing values
print("--- Missing Values After Imputation ---")
print(orders_clean[['discount_pct', 'rating']].isnull().sum())

## Task 5 - Merge and reconcile against Part 1

# Merge orders with products
orders_clean = pd.merge(orders_clean, products,
    on='product_id', how='left'
)

# Merge orders with customers
orders_clean = pd.merge(orders_clean, customers,
    on='customer_id', how='left'
)

# Calculate order value after discount
orders_clean['order_value'] = (
    orders_clean['quantity'] * orders_clean['price'] * (1 - orders_clean['discount_pct'] / 100)
)

# Calculate total cleaned revenue
cleaned_revenue = orders_clean['order_value'].sum()

print("CLEANED TOTAL ORDER VALUE:", round(cleaned_revenue, 2))

# Get the 5 duplicate rows that were removed
dropped_orders = orders.loc[duplicate_mask].copy()

# Merge dropped orders with products to get price
dropped_orders = pd.merge(
    dropped_orders, products[['product_id', 'price']],
    on='product_id', how='left')

# Calculate their order value
dropped_orders['order_value'] = (
    dropped_orders['quantity'] * dropped_orders['price'] * (1 - dropped_orders['discount_pct'] / 100)
)

print("DUPLICATE ORDER VALUE REMOVED:", round(dropped_orders['order_value'].sum(), 2))

"""*Reconciliation Note*

The total order value reconciled post clean up in python **(₹ 97358.30)** is different from the total value calculated in the SQL **(₹ 99860.20)** with a difference of value as **₹ 2501.90**. The difference is an attributable post data clean up by removal by 5 Duplicate Rows with rating & discount imputation having no effect on the final result. Data provided without any missing or incorrect data will help on hypothesis and analysis for Reporting.
"""

##	Task 6 - IQR outlier detection on quantity

# Calculate Q1, Q3 and IQR for quantity
q1, q3 = np.percentile(orders_clean['quantity'], [25, 75])
iqr = q3 - q1

lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

print("-- IQR Outlier Detection --")
print("Q1:", q1)
print("Q3:", q3)
print("IQR:", iqr)
print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)

# Identify outliers
orders_clean['is_outlier'] = (
    (orders_clean['quantity'] < lower_bound) |
    (orders_clean['quantity'] > upper_bound)
)

# Print outlier rows without dropping the rows
print("\n -- Outlier Orders --")
print(orders_clean.loc[orders_clean['is_outlier'], ['order_id', 'quantity']])

## Task 7 - Hypothesis: does COD have a higher return rate?

## Step 1 - Summary statistics

print("--- orders data clean for schema prompt & hypothesis ---")

print("=== SHAPE ===")
print(orders_clean.shape)

print("\n=== DATA TYPES ===")
print(orders_clean.dtypes)

print("\n=== NUMERIC SUMMARY ===")
print(orders_clean[['order_value','discount_pct','rating','returned']].describe().round(1))

print("\n=== CATEGORICAL COUNTS ===")
for col in ['payment_method','returned']:
  print(f"\n{col}:")
  print(orders_clean[col].value_counts())

## STEP 2 - the schema prompt to send to your AI tool
# (copy this, paste your actual output from above into the [PASTE HERE] section,
# and send the whole thing to ChatGPT / Claude / Gemini)

schema_prompt = """
You are an experienced Data Analyst working with Mamaearth's Growth Analytics Team
helping understand the reason behind returns and margins on a subset of orders

DATASET: Mamaearth's - Orders Data
ROWS: 175 order lines

SUMMARY STATISTICS:
--- orders data clean for schema prompt & hypothesis ---
=== SHAPE ===
(175, 19)

=== DATA TYPES ===
order_id               object
customer_id            object
product_id             object
order_date             object
quantity                int64
discount_pct          float64
payment_method         object
rating                 float64
returned                int64
product_name           object
category               object
price                   int64
name                   object
city                    object
city_tier               int64
signup_date             object
acquisition_source      object
order_value            float64
is_outlier               bool
dtype: object

=== NUMERIC SUMMARY ===
       order_value  discount_pct  rating  returned
count        175.0         175.0   175.0     175.0
mean         556.3          16.7     3.0       0.3
std          968.8          11.5     1.4       0.4
min          139.3           0.0     1.0       0.0
25%          241.8          10.0     2.0       0.0
50%          359.2          20.0     3.0       0.0
75%          571.7          30.0     4.0       0.5
max        10470.0          30.0     5.0       1.0

=== CATEGORICAL COUNTS ===

payment_method:
payment_method
CARD    68
COD     54
UPI     53
Name: count, dtype: int64

returned:
returned
0    131
1     44
Name: count, dtype: int64

TASK: Generate exactly 2-3 testable hypotheses related to the company's growth trajectory.
Each hypothesis should:
- Refer to specific column names
- Include a clear relationship between the columns

CONSTRAINTS:
- No hypotheses about data quality or missing values
- Each hypothesis must be different from the others
- Do not explain how to test the hypothesis

FORMAT: Numbered list. Each item: hypothesis in one sentence,
then one sentence on why it would be business-relevant if confirmed.
"""

print(schema_prompt)

"""1. **Hypothesis:** Orders using `payment_method` COD have a higher `returned` rate than orders using CARD or UPI.  
   If confirmed, reducing COD-related return risk could improve order profitability and support healthier growth.

2. **Hypothesis:** ## Validating the Second Hypotheses that Higher `discount_pct` decreases `returned` orders rate.   
   If confirmed, optimizing discount levels could help protect margins while maintaining customer demand.

3. **Hypothesis:** Orders with higher `rating` have a lower `returned` rate.  
   If confirmed, improving customer satisfaction could help reduce returns and support sustainable growth.
"""

## STEP 3: Validating the First Hypothesis through groupby method

category_avg = orders_clean.groupby('payment_method')['returned'].agg(['count', 'mean'])
category_avg['mean'] = (category_avg['mean'] * 100)
print(f"{(category_avg).round(1)}")

"""**Verdict: Confirmed.** COD has a higher return rate than any other payment method, with **44.4%** of COD orders being returned, which is almost half of the orders made through COD."""

##	Task 8 - Multi-level segmentation: multi column groupby -> payment + city_tier
# Return rate by category AND payment — simultaneously

return_by_payment = orders_clean.groupby(['payment_method', 'city_tier']).agg(
    total_orders=('returned', 'count'),
    returned_orders=('returned', 'sum'),
    return_rate=('returned', 'mean')
)

return_by_payment['return_rate'] = (
    return_by_payment['return_rate'] * 100
).round(1)

return_by_payment.sort_values('return_rate', ascending=False)

"""Through Multi Segmentation, the data reveals as follows:

- COD payment method used in Tier 2 cities has the highest return rate at 54.5%, creating a higher risk of return for future orders and requiring further analysis and bifurcation across other categories.

- Even with a 37.5% return rate, COD payment method used in Tier 1 cities has a relatively lower risk of return compared to Tier 2 cities.

- The safest payment method is CARD used in Tier 1 cities, with the lowest return rate.

KEY INSIGHT: COD risk is not uniform across city tiers.
"""

##	Task 9 - Correlation analysis

## Validating the Second Hypotheses that Higher `discount_pct` decreases `returned` orders rate

matrix_corr = ['rating', 'returned', 'discount_pct', 'quantity']

correlated_matrix = orders_clean[matrix_corr].corr().round(2)

correlated_matrix

"""There are six pairs made to review the coorelation, but all the six pairs does have negligble coorelation with matrix all below 0.19 (+/-).

**Verdict: Busted**  There is no meaningful coorelation between discount_pct and return rate as the correlation falls within the negligible range. Therefore, higher discounts do not appear to be associated with a reduction in returned orders.
"""

##	Task 10 - Outlier-corrected time series

# 1. Convert order_date to datetime, extract year-month, compute monthly total order_value with outlier:
orders_clean['order_date'] = pd.to_datetime(orders_clean['order_date'])
orders_clean['year_month'] = orders_clean['order_date'].dt.to_period('M')

monthly_order_value = orders_clean.groupby('year_month')['order_value'].sum().round(2)

print("-- Monthly Order Value --")
print(monthly_order_value) ## Including the outliers and extreme values

# 2. Monthly order value excluding outliers
o2_corrected_monthly_order_value = (orders_clean[~orders_clean['is_outlier']]
    .groupby('year_month')['order_value'].sum().round(2)
)

print("\n-- Monthly Order Value Excluding Outliers --")
print(o2_corrected_monthly_order_value)
plt.show()
