# -*- coding: utf-8 -*-
"""clean_and_eda

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iB6vCBRZA5X7NuNn-bxXBEaOcnNP_35O

# *Part 2 - Python/Pandas Data Wrangling & EDA*

1.	Task 1 - Load and inspect
2.	Task 2 - Standardize payment_method casing
3.	Task 3 - Remove duplicate orders
4.	Task 4 - Impute missing values
5.	Task 5 - Merge and reconcile against Part 1
6.	Task 6 - IQR outlier detection on quantity
7.	Task 7 - Hypothesis: does COD have a higher return rate?
8.	Task 8 - Multi-level segmentation
9.	Task 9 - Correlation analysis
10.	Task 10 - Outlier-corrected time series
11.	Task 11 - Two visualizations (analysis/visualize.py)
"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import statistics as stats
import seaborn as sns

## LOAD AND INSPECT

customers = pd.read_csv('/content/DATA_CUSTOMERS.csv')
# print("=== CUSTOMERS DATA SHAPE ===")
# print(customers.shape)

orders = pd.read_csv('/content/DATA_ORDERS.csv')
# print("=== ORDERS DATA SHAPE ===")
# print(orders.shape)

products = pd.read_csv('/content/DATA_PRODUCTS.csv')
# print("=== PRODUCTS DATA SHAPE ===")
# print(products.shape)

## Before cleaning
# orders.head()

## Task 2 - Standardize payment_method casing

## Correct casing of payment_method to make it more cohesive
orders['payment_method'] = orders['payment_method'].str.strip().str.upper()

print(f"PAYMENT METHOD: {orders['payment_method'].unique()}")

## Payment_Method head counts
orders['payment_method'].value_counts()

## Task 3 - Remove duplicate orders

# Identify duplicates using the natural key.
# order_id is excluded because O0176-O0180 have different IDs by design.
duplicate_mask = orders.duplicated(
    subset=[
        'customer_id', 'product_id', 'order_date', 'quantity',
        'discount_pct', 'payment_method', 'rating', 'returned'
    ],
    keep='first'
)

# Print the duplicate order IDs
print("DUPLICATE ORDER IDs:")
print(orders.loc[duplicate_mask, 'order_id'])

# Remove duplicate rows
orders_clean = orders[~duplicate_mask].copy()

# Check the cleaned shape
print("CLEANED DATA SHAPE:", orders_clean.shape)

## Task 4 - Impute missing values

# Fill missing discount values with 0
orders_clean['discount_pct'] = orders_clean['discount_pct'].fillna(0)

# Calculate median rating before imputation
rating_median = orders_clean['rating'].median()
print("MEDIAN RATING:", rating_median)

# Count the rows which were missing the values for imputation
print("--- Missing Values Before Imputation ---")
print(orders[['discount_pct', 'rating']].isnull().sum())

# Fill missing ratings with the median
orders_clean['rating'] = orders_clean['rating'].fillna(rating_median)

# Check for remaining missing values
print("--- Missing Values After Imputation ---")
print(orders_clean[['discount_pct', 'rating']].isnull().sum())

## Task 5 - Merge and reconcile against Part 1

# Merge orders with products
orders_clean = pd.merge(orders_clean, products,
    on='product_id', how='left'
)

# Merge orders with customers
orders_clean = pd.merge(orders_clean, customers,
    on='customer_id', how='left'
)

# Calculate order value after discount
orders_clean['order_value'] = (
    orders_clean['quantity'] * orders_clean['price'] * (1 - orders_clean['discount_pct'] / 100)
)

# Calculate total cleaned revenue
cleaned_revenue = orders_clean['order_value'].sum()

print("CLEANED TOTAL ORDER VALUE:", round(cleaned_revenue, 2))

# Get the 5 duplicate rows that were removed
dropped_orders = orders.loc[duplicate_mask].copy()

# Merge dropped orders with products to get price
dropped_orders = pd.merge(
    dropped_orders, products[['product_id', 'price']],
    on='product_id', how='left')

# Calculate their order value
dropped_orders['order_value'] = (
    dropped_orders['quantity'] * dropped_orders['price'] * (1 - dropped_orders['discount_pct'] / 100)
)

print("DUPLICATE ORDER VALUE REMOVED:", round(dropped_orders['order_value'].sum(), 2))

"""*Reconciliation Note*

The total order value reconciled post clean up in python **(₹ 97358.30)** is different from the total value calculated in the SQL **(₹ 99860.20)** with a difference of value as **₹ 2501.90**. The difference is an attributable post data clean up by removal by 5 Duplicate Rows with rating & discount imputation having no effect on the final result. Data provided without any missing or incorrect data will help on hypothesis and analysis for Reporting.
"""

##	Task 6 - IQR outlier detection on quantity

# Calculate Q1, Q3 and IQR for quantity
q1, q3 = np.percentile(orders_clean['quantity'], [25, 75])
iqr = q3 - q1

lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

print("-- IQR Outlier Detection --")
print("Q1:", q1)
print("Q3:", q3)
print("IQR:", iqr)
print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)

# Identify outliers
orders_clean['is_outlier'] = (
    (orders_clean['quantity'] < lower_bound) |
    (orders_clean['quantity'] > upper_bound)
)

# Print outlier rows without dropping the rows
print("\n -- Outlier Orders --")
print(orders_clean.loc[orders_clean['is_outlier'], ['order_id', 'quantity']])

## Task 7 - Hypothesis: does COD have a higher return rate?

## Step 1 - Summary statistics

print("--- orders data clean for schema prompt & hypothesis ---")

print("=== SHAPE ===")
print(orders_clean.shape)

print("\n=== DATA TYPES ===")
print(orders_clean.dtypes)

print("\n=== NUMERIC SUMMARY ===")
print(orders_clean[['order_value','discount_pct','rating','returned']].describe().round(1))

print("\n=== CATEGORICAL COUNTS ===")
for col in ['payment_method','returned']:
  print(f"\n{col}:")
  print(orders_clean[col].value_counts())

## STEP 2 - the schema prompt to send to your AI tool
# (copy this, paste your actual output from above into the [PASTE HERE] section,
# and send the whole thing to ChatGPT / Claude / Gemini)

schema_prompt = """
You are an experienced Data Analyst working with Mamaearth's Growth Analytics Team
helping understand the reason behind returns and margins on a subset of orders

DATASET: Mamaearth's - Orders Data
ROWS: 175 order lines

SUMMARY STATISTICS:
--- orders data clean for schema prompt & hypothesis ---
=== SHAPE ===
(175, 19)

=== DATA TYPES ===
order_id               object
customer_id            object
product_id             object
order_date             object
quantity                int64
discount_pct          float64
payment_method         object
rating                 float64
returned                int64
product_name           object
category               object
price                   int64
name                   object
city                    object
city_tier               int64
signup_date             object
acquisition_source      object
order_value            float64
is_outlier               bool
dtype: object

=== NUMERIC SUMMARY ===
       order_value  discount_pct  rating  returned
count        175.0         175.0   175.0     175.0
mean         556.3          16.7     3.0       0.3
std          968.8          11.5     1.4       0.4
min          139.3           0.0     1.0       0.0
25%          241.8          10.0     2.0       0.0
50%          359.2          20.0     3.0       0.0
75%          571.7          30.0     4.0       0.5
max        10470.0          30.0     5.0       1.0

=== CATEGORICAL COUNTS ===

payment_method:
payment_method
CARD    68
COD     54
UPI     53
Name: count, dtype: int64

returned:
returned
0    131
1     44
Name: count, dtype: int64

TASK: Generate exactly 2-3 testable hypotheses related to the company's growth trajectory.
Each hypothesis should:
- Refer to specific column names
- Include a clear relationship between the columns

CONSTRAINTS:
- No hypotheses about data quality or missing values
- Each hypothesis must be different from the others
- Do not explain how to test the hypothesis

FORMAT: Numbered list. Each item: hypothesis in one sentence,
then one sentence on why it would be business-relevant if confirmed.
"""

print(schema_prompt)

"""1. **Hypothesis:** Orders using `payment_method` COD have a higher `returned` rate than orders using CARD or UPI.  
   If confirmed, reducing COD-related return risk could improve order profitability and support healthier growth.

2. **Hypothesis:** ## Validating the Second Hypotheses that Higher `discount_pct` decreases `returned` orders rate.   
   If confirmed, optimizing discount levels could help protect margins while maintaining customer demand.

3. **Hypothesis:** Orders with higher `rating` have a lower `returned` rate.  
   If confirmed, improving customer satisfaction could help reduce returns and support sustainable growth.
"""

## STEP 3: Validating the First Hypothesis through groupby method

category_avg = orders_clean.groupby('payment_method')['returned'].agg(['count', 'mean'])
category_avg['mean'] = (category_avg['mean'] * 100)
print(f"{(category_avg).round(1)}")

"""**Verdict: Confirmed.** COD has a higher return rate than any other payment method, with **44.4%** of COD orders being returned, which is almost half of the orders made through COD."""

##	Task 8 - Multi-level segmentation: multi column groupby -> payment + city_tier
# Return rate by category AND payment — simultaneously

return_by_payment = orders_clean.groupby(['payment_method', 'city_tier']).agg(
    total_orders=('returned', 'count'),
    returned_orders=('returned', 'sum'),
    return_rate=('returned', 'mean')
)

return_by_payment['return_rate'] = (
    return_by_payment['return_rate'] * 100
).round(1)

return_by_payment.sort_values('return_rate', ascending=False)

"""Through Multi Segmentation, the data reveals as follows:

- COD payment method used in Tier 2 cities has the highest return rate at 54.5%, creating a higher risk of return for future orders and requiring further analysis and bifurcation across other categories.

- Even with a 37.5% return rate, COD payment method used in Tier 1 cities has a relatively lower risk of return compared to Tier 2 cities.

- The safest payment method is CARD used in Tier 1 cities, with the lowest return rate.

KEY INSIGHT: COD risk is not uniform across city tiers.
"""

##	Task 9 - Correlation analysis

## Validating the Second Hypotheses that Higher `discount_pct` decreases `returned` orders rate

matrix_corr = ['rating', 'returned', 'discount_pct', 'quantity']

correlated_matrix = orders_clean[matrix_corr].corr().round(2)

correlated_matrix

"""There are six pairs made to review the coorelation, but all the six pairs does have negligble coorelation with matrix all below 0.19 (+/-).

**Verdict: Busted**  There is no meaningful coorelation between discount_pct and return rate as the correlation falls within the negligible range. Therefore, higher discounts do not appear to be associated with a reduction in returned orders.
"""

##	Task 10 - Outlier-corrected time series

# 1. Convert order_date to datetime, extract year-month, compute monthly total order_value with outlier:
orders_clean['order_date'] = pd.to_datetime(orders_clean['order_date'])
orders_clean['year_month'] = orders_clean['order_date'].dt.to_period('M')

monthly_order_value = orders_clean.groupby('year_month')['order_value'].sum().round(2)

print("-- Monthly Order Value --")
print(monthly_order_value) ## Including the outliers and extreme values

# 2. Monthly order value excluding outliers
o2_corrected_monthly_order_value = (orders_clean[~orders_clean['is_outlier']]
    .groupby('year_month')['order_value'].sum().round(2)
)

print("\n-- Monthly Order Value Excluding Outliers --")
print(o2_corrected_monthly_order_value)

"""Additional Analysis for Narrative"""

# Hypothesis 3: Do higher ratings relate to lower return rates?

rating_return = orders_clean.groupby('rating')['returned'].agg(
    total_orders='count',
    returned_orders='sum',
    return_rate='mean'
)

rating_return['return_rate_pct'] = (
    rating_return['return_rate'] * 100
).round(1)

print(rating_return)

"""**Verdict: Busted**

Return rates vary across rating groups, ranging from 16.7% for 4-star orders to 39.1% for 2-star orders. However, the pattern is not consistently decreasing with higher ratings, so the hypothesis that higher ratings are associated with fewer returns is not conclusively supported.

Hypothesis 4
Higher-value COD orders have a higher return rate than lower-value COD orders.
"""

# Hypothesis 4: Does order value relate to return rate for COD orders?

cod_orders = orders_clean[
    orders_clean['payment_method'] == 'COD'
].copy()

# Divide COD orders into 3 order-value groups
cod_orders['value_group'] = pd.qcut(
    cod_orders['order_value'],
    q=3,
    labels=['Low Value', 'Medium Value', 'High Value'],
    duplicates='drop'
)

# Calculate return rate for each value group
cod_value_return = cod_orders.groupby(
    'value_group', observed=True
)['returned'].agg(
    total_orders='count',
    returned_orders='sum',
    return_rate='mean'
)

cod_value_return['return_rate_pct'] = (
    cod_value_return['return_rate'] * 100
).round(1)

print(cod_value_return)

"""**Verdict: Confirmed.** The result supports an association between high order value and higher COD return rates in this dataset. It does not establish causation, and each group contains only 18 orders, so further validation would be useful."""

# Compare COD return rates by city tier and order-value group

cod_orders = orders_clean[
    orders_clean['payment_method'] == 'COD'
].copy()

cod_orders['value_group'] = pd.qcut(
    cod_orders['order_value'],
    q=3,
    labels=['Low Value', 'Medium Value', 'High Value'],
    duplicates='drop'
)

cod_tier_value_return = cod_orders.groupby(
    ['city_tier', 'value_group'],
    observed=True
)['returned'].agg(
    total_orders='count',
    returned_orders='sum',
    return_rate='mean'
)

cod_tier_value_return['return_rate_pct'] = (
    cod_tier_value_return['return_rate'] * 100
).round(1)

cod_tier_value_return

"""**Hypothesis verdict: Supported descriptively **

The combination of Tier 2 city, COD payment, and high order value is associated with a higher return rate in this dataset. The small sample sizes mean we should validate this pattern before treating it as a stable business rule.
"""

# Hypothesis 4: High-value COD orders in Tier 2 cities
# have a higher return rate than other COD order-value segments.

print("HYPOTHESIS 4 — HIGH-VALUE COD ORDERS BY CITY TIER")
print(cod_tier_value_return)

print(
    "Finding: High-value COD orders in Tier 2 cities had a "
    "return rate of 87.5% (7 out of 8 orders)."
)

"""Hypothesis: High-value COD orders in Tier 2 cities have a higher return rate than other COD order-value segments."""

# Hypothesis 4: High-value COD orders in Tier 2 cities

cod_orders = orders_clean[
    orders_clean['payment_method'] == 'COD'
].copy()

cod_orders['value_group'] = pd.qcut(
    cod_orders['order_value'],
    q=3,
    labels=['Low Value', 'Medium Value', 'High Value'],
    duplicates='drop'
)

hypothesis_4 = (
    cod_orders
    .groupby(['city_tier', 'value_group'], observed=True)
    .agg(
        total_orders=('returned', 'count'),
        returned_orders=('returned', 'sum'),
        return_rate=('returned', 'mean')
    )
    .reset_index()
)

hypothesis_4['return_rate_pct'] = (
    hypothesis_4['return_rate'] * 100
).round(1)

hypothesis_4

# Check order-value thresholds for COD groups

value_thresholds = cod_orders.groupby(
    'value_group', observed=True
).agg(
    min_order_value=('order_value', 'min'),
    max_order_value=('order_value', 'max'),
    average_order_value=('order_value', 'mean'),
    total_orders=('returned', 'count'),
    returned_orders=('returned', 'sum')
)

value_thresholds['return_rate_pct'] = (
    value_thresholds['returned_orders']
    / value_thresholds['total_orders'] * 100
).round(1)

value_thresholds[
    ['min_order_value', 'max_order_value', 'average_order_value',
     'total_orders', 'returned_orders', 'return_rate_pct']
] = value_thresholds[
    ['min_order_value', 'max_order_value', 'average_order_value',
     'total_orders', 'returned_orders', 'return_rate_pct']
].round(2)

value_thresholds

print(cod_orders.groupby('value_group', observed=True)['order_value'].agg(
    ['min', 'max']
))

print("\nQuantile cut-off points:")
print(pd.qcut(
    cod_orders['order_value'],
    q=3,
    retbins=True,
    duplicates='drop'
)[1])

"""Hypothesis: High-value COD orders in Tier 2 cities have a higher return rate than other COD order-value segments.
Verdict: Supported descriptively, with a small-sample caveat.
- High-value COD orders overall: 66.7% return rate (12 of 18).
- High-value COD in Tier 2: 87.5% (7 of 8).
- High-value COD in Tier 1: 50.0% (5 of 10).
The data suggests that the combination of high order value, COD payment, and Tier 2 city is associated with elevated return risk. It does not prove causation, and the Tier 2 high-value segment has only eight orders.
"""

# Hypothesis 4: COD order value and city-tier return risk

cod_orders = orders_clean[
    orders_clean['payment_method'] == 'COD'
].copy()

cod_orders['value_group'] = pd.qcut(
    cod_orders['order_value'],
    q=3,
    labels=['Low Value', 'Medium Value', 'High Value'],
    duplicates='drop'
)

cod_tier_value_return = (
    cod_orders.groupby(
        ['city_tier', 'value_group'], observed=True
    )['returned']
    .agg(total_orders='count', returned_orders='sum', return_rate='mean')
)

cod_tier_value_return['return_rate_pct'] = (
    cod_tier_value_return['return_rate'] * 100
).round(1)

_, value_cutoffs = pd.qcut(
    cod_orders['order_value'],
    q=3,
    retbins=True,
    duplicates='drop'
)

import json #### This includes the additional hypotheses to find a solution for resolution & improvement

# Save cleaned dataset for visualize.py
orders_clean.to_csv('/content/orders_clean.csv', index=False)

# Define the raw total revenue from SQL (Part 1)
raw_total_revenue = 99860.2

# Create verified findings for Part 3
findings = {
    "cleaned_total_revenue_inr": round(cleaned_revenue, 2),
    "raw_total_revenue_inr": round(raw_total_revenue, 2),
    "duplicate_reconciliation_delta_inr": round(
        dropped_orders['order_value'].sum(), 2
    ),

    "return_rate_by_payment": {
        "COD": round(category_avg.loc['COD', 'mean'], 1),
        "CARD": round(category_avg.loc['CARD', 'mean'], 1),
        "UPI": round(category_avg.loc['UPI', 'mean'], 1)
    },

    "highest_risk_segment": {
        "payment_method": "COD",
        "city_tier": 2,
        "return_rate_pct": round(
            return_by_payment.loc[('COD', 2), 'return_rate'], 1
        )
    },

    "true_peak_month": {
        "month": str(o2_corrected_monthly_order_value.idxmax()),
        "revenue_inr": round(
            o2_corrected_monthly_order_value.max(), 2
        )
    },

    "outlier_inflated_month": {
        "month": str(monthly_order_value.idxmax()),
        "apparent_revenue_inr": round(
            monthly_order_value.max(), 2
        ),
        "corrected_revenue_inr": round(
            o2_corrected_monthly_order_value.loc[
                monthly_order_value.idxmax()
            ], 2
        )
    },

    "cod_return_rate_by_value": {
        str(group): {
            "total_orders": int(row["total_orders"]),
            "returned_orders": int(row["returned_orders"]),
            "return_rate_pct": float(row["return_rate_pct"])
        }
        for group, row in cod_value_return.iterrows()
    },

    "cod_return_rate_by_tier_and_value": [
        {
            "city_tier": int(idx[0]),
            "value_group": str(idx[1]),
            "total_orders": int(row["total_orders"]),
            "returned_orders": int(row["returned_orders"]),
            "return_rate_pct": float(row["return_rate_pct"])
        }
        for idx, row in cod_tier_value_return.iterrows()
    ],

    "cod_order_value_quantile_cutoffs_inr": [
        round(float(value), 2) for value in value_cutoffs
    ]
}

# Write findings.json for Part 3 (saving directly to /content/findings.json)
with open('/content/findings.json', 'w') as f:
    json.dump(findings, f, indent=4)

print("\n=== FINDINGS.JSON CREATED ===")
print(json.dumps(findings, indent=4))
